### ISSUE TITLE
Criar as classes de repositório das classes do domínio (User, Vehicle e Station)

### ISSUE THREAD

**Issue by jamillosantos** [jamillosantos/postolegal#28]
#### Informações do slide
Criar uma classe repositório para cada uma das classes de domínio. Ela deve extender a classe RepositorioEmMemoria, sem necessitar implementar nenhum método CRUD.

#### Descrição
**Os tópicos a seguir devem ser aplicadas as classes `User`, `Vehicle`, `Station`.**

* Criar interfaces para os repositórios, extendendo de `Repository<T>` (sendo `T` uma classe de domínio);
* Criar classes para os repositórios, extendendo de `RepositoryInMemory<T>` (sendo `T` uma classe de domínio);
    * Estas classes devem ser anotadas com `@Named`;

#### Dependencias
* Tarefa #22 

#### Relacionadas
* Tarefa #23

**Comment by JulianSansat** [comment]
tarefa #28 implmentada no commit da tarefa #30
