### ISSUE TITLE
Criar teste de integração para repositórios (User, Vehicle e Station)

### ISSUE THREAD

**Issue by jamillosantos** [jamillosantos/postolegal#29]
#### Informações do slide
Criar teste de integração para cada uma das classes repositório das classes de domínio.

#### Descrição
**Os tópicos a seguir devem ser aplicados as classes `User`, `Vehicle` e `Station`.**

* Criar teste de integração para o repositório criado na tarefa #28.

#### Dependencias
* Tarefa #28.

**Comment by jamillosantos** [comment]
Foi criado um modelo dos testes de integração de repositório em https://github.com/jamillosantos/postolegal/tree/master/src/test/java/br/edu/ifrn/postolegal/persistence

**Comment by renatosoares** [comment]
@jamillosantos testes aplicados nas classes User e Station.

**Comment by renatosoares** [comment]
@jamillosantos nesses métodos ([protected Station createObject()] [protected User createObject()]) esta acontecendo erros que preciso ver com professor o motivo.
