### ISSUE TITLE
Criar classes de serviço (User, Vehicle e Station)

### ISSUE THREAD

**Issue by jamillosantos** [jamillosantos/postolegal#30]
#### Informações do slide
Criar uma classe Servico para cada uma das classes de domínio. Ele deve extender a classe ServicoAbstrato, sem necessitar implementar nenhum método CRUD.

#### Descrição
**Os tópicos a seguir devem ser aplicados as classes `User`, `Vehicle` e `Station`.**

* Criar classes de serviço extendendo de `Service<T>`;
* Anotar classes de serviço com `@Named`;
* Anotar injeção de dependência do repositório correspondente com `@Inject`.

#### Dependências
* Tarefa #25;
* Tarefa #23.

**Comment by renatosoares** [comment]
@jamillosantos , @JulianSansat vou fazer as classes User e Station

**Comment by renatosoares** [comment]
@jamillosantos classes User e Station concluídas, se tiver algo a ser corrigido faremos isso na terça. :+1:
