### ISSUE TITLE
Criar teste de integração para serviço (User, Vehicle e Station)

### ISSUE THREAD

**Issue by jamillosantos** [jamillosantos/postolegal#31]
#### Informações do slide
Criar teste de integração para cada uma das classes de serviço das classes de domínio.

#### Descrição
**Os tópicos a seguir devem ser aplicados as classes `User`, `Vehicle` e `Station`.**

* Criar teste de integração da classe de serviço correspondente;

#### Dependências
* Tarefa #30.

**Comment by jamillosantos** [comment]
Modelo dos testes de integração para serviço em https://github.com/jamillosantos/postolegal/tree/master/src/test/java/br/edu/ifrn/postolegal/service

**Comment by renatosoares** [comment]
@jamillosantos testes feito para as classes User e Station
