### ISSUE TITLE
Criar os testes unitários dos métodos `equals` e `compareTo` das classes de domínio

### ISSUE THREAD

**Issue by jamillosantos** [jamillosantos/postolegal#6]
@renatosoares : Definir quais classes serão implementadas e criar a outra tarefa para @JulianSansat.

**Comment by renatosoares** [comment]
@jamillosantos serão essas as classes que irei implementar (Consumption, Product, User, Vehicle)

**Comment by renatosoares** [comment]
@jamillosantos são essas as que implementarei Consumption, Product, User, Vehicle

**Comment by jamillosantos** [comment]
@renatosoares, os casos de teste não estão funcionando. Aliás, analisando o código gerado, eles nem funcionariam. Você pode verificar o funcionamento deles?

**Comment by JulianSansat** [comment]
As classes que estiverem faltando realizar os testes ficam comigo, que farei na quinta feira.

**Comment by JulianSansat** [comment]
Se eu não me engano é para usar tesNG e AssertJ, já estão configurados?

**Comment by JulianSansat** [comment]
Implementando os testes de Station, StationProduct, StationProductHistory, StationProductId,
